// AstroData.ts

export const zodiacData = [
  {
    id: 1,
    name: "Aries",
    date: "Mar 21 - Apr 19",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-ppp.jpg",
    description: "Start your journey with courage and energy.",
    traits: [
      "Courageous",
      "Energetic",
      "Pioneering",
      "Adventurous",
      "Confident",
    ],
    element: "Fire",
    planet: "Mars",
    symbol: "♈",
    luckyColor: "Red",
    luckyNumber: 9,
    compatibility: ["Leo", "Sagittarius", "Gemini"],
    benefits: [
      "Understand your natural leadership qualities",
      "Harness your dynamic energy effectively",
      "Make confident career decisions",
      "Improve relationships through better understanding",
      "Plan your financial growth strategically",
    ],
    readingIncludes: [
      "Detailed personality analysis",
      "Career and financial guidance",
      "Relationship compatibility",
      "Monthly horoscope predictions",
      "Personalized remedies and solutions",
    ],
    strengths: ["Leadership", "Courage", "Initiative", "Honesty"],
    challenges: ["Impatience", "Aggression", "Selfishness"],
  },
  {
    id: 2,
    name: "Taurus",
    date: "Apr 20 - May 20",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-pp.png",
    description: "Steadiness and patience will guide you.",
    traits: ["Reliable", "Patient", "Practical", "Loyal", "Sensual"],
    element: "Earth",
    planet: "Venus",
    symbol: "♉",
    luckyColor: "Green",
    luckyNumber: 6,
    compatibility: ["Virgo", "Capricorn", "Cancer"],
    benefits: [
      "Develop financial stability and security",
      "Enhance relationship harmony and trust",
      "Find practical solutions to life challenges",
      "Improve decision-making skills with clarity",
      "Achieve long-term goals with determination",
    ],
    readingIncludes: [
      "Financial prosperity analysis",
      "Love and relationship guidance",
      "Personality deep dive",
      "Future predictions and opportunities",
      "Customized practical solutions",
    ],
    strengths: ["Reliability", "Patience", "Loyalty", "Practicality"],
    challenges: ["Stubbornness", "Possessiveness", "Resistance to change"],
  },
  {
    id: 3,
    name: "Gemini",
    date: "May 21 - Jun 20",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-ddd.jpg",
    description: "Embrace curiosity and adaptability.",
    traits: ["Adaptable", "Curious", "Expressive", "Witty", "Intelligent"],
    element: "Air",
    planet: "Mercury",
    symbol: "♊",
    luckyColor: "Yellow",
    luckyNumber: 5,
    compatibility: ["Libra", "Aquarius", "Aries"],
    benefits: [
      "Enhance communication skills and creativity",
      "Understand and balance dual personality traits",
      "Balance emotions with logical thinking",
      "Improve networking and social relationships",
      "Plan career based on natural intellectual skills",
    ],
    readingIncludes: [
      "Communication enhancement guide",
      "Personality duality analysis",
      "Career and education guidance",
      "Social relationship improvement",
      "Mental clarity techniques",
    ],
    strengths: ["Adaptability", "Intelligence", "Communication", "Curiosity"],
    challenges: ["Nervousness", "Inconsistency", "Superficiality"],
  },
  {
    id: 4,
    name: "Cancer",
    date: "Jun 21 - Jul 22",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-l.jpg",
    description: "Trust your intuition and emotions.",
    traits: ["Emotional", "Caring", "Intuitive", "Protective", "Nurturing"],
    element: "Water",
    planet: "Moon",
    symbol: "♋",
    luckyColor: "Silver",
    luckyNumber: 2,
    compatibility: ["Scorpio", "Pisces", "Taurus"],
    benefits: [
      "Gain emotional stability and security",
      "Strengthen family and home relationships",
      "Nurture your creativity and intuition",
      "Plan personal and professional growth",
      "Understand hidden emotional patterns for healing",
    ],
    readingIncludes: [
      "Emotional intelligence analysis",
      "Family and home life guidance",
      "Intuition development techniques",
      "Personal growth planning",
      "Healing and nurturing practices",
    ],
    strengths: ["Loyalty", "Emotional depth", "Nurturing", "Intuition"],
    challenges: ["Moodiness", "Over-sensitivity", "Clinginess"],
  },
  {
    id: 5,
    name: "Leo",
    date: "Jul 23 - Aug 22",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-eee.jpg",
    description: "Confidence and creativity lead the way.",
    traits: ["Confident", "Generous", "Creative", "Passionate", "Leadership"],
    element: "Fire",
    planet: "Sun",
    symbol: "♌",
    luckyColor: "Gold",
    luckyNumber: 1,
    compatibility: ["Aries", "Sagittarius", "Libra"],
    benefits: [
      "Boost self-confidence and leadership abilities",
      "Attract success and recognition naturally",
      "Balance ego with humility for better relationships",
      "Enhance creative abilities and self-expression",
      "Plan a powerful personal and professional journey",
    ],
    readingIncludes: [
      "Leadership potential analysis",
      "Creative expression guidance",
      "Recognition and success planning",
      "Relationship harmony techniques",
      "Personal power enhancement",
    ],
    strengths: ["Confidence", "Generosity", "Creativity", "Leadership"],
    challenges: ["Arrogance", "Dramatic", "Stubbornness"],
  },
  {
    id: 6,
    name: "Virgo",
    date: "Aug 23 - Sep 22",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-pppp.jpg",
    description: "Focus on details and practical solutions.",
    traits: ["Analytical", "Reliable", "Perfectionist", "Practical", "Helpful"],
    element: "Earth",
    planet: "Mercury",
    symbol: "♍",
    luckyColor: "Navy Blue",
    luckyNumber: 5,
    compatibility: ["Taurus", "Capricorn", "Cancer"],
    benefits: [
      "Improve organizational and planning skills",
      "Overcome overthinking and stress management",
      "Balance work-life responsibilities effectively",
      "Strengthen career growth with logical approach",
      "Enhance health and wellness focus for better living",
    ],
    readingIncludes: [
      "Analytical skills enhancement",
      "Stress management techniques",
      "Career optimization guidance",
      "Health and wellness planning",
      "Practical life solutions",
    ],
    strengths: ["Analytical", "Reliable", "Hardworking", "Practical"],
    challenges: ["Over-critical", "Worrying", "Perfectionism"],
  },
  {
    id: 7,
    name: "Libra",
    date: "Sep 23 - Oct 22",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-dddd.jpg",
    description: "Balance and harmony will guide decisions.",
    traits: ["Charming", "Diplomatic", "Balanced", "Social", "Fair-minded"],
    element: "Air",
    planet: "Venus",
    symbol: "♎",
    luckyColor: "Pink",
    luckyNumber: 6,
    compatibility: ["Gemini", "Aquarius", "Leo"],
    benefits: [
      "Achieve emotional and professional balance",
      "Attract love and peace in relationships",
      "Strengthen partnerships and social bonds",
      "Improve decision-making with clarity and fairness",
      "Plan artistic and creative pursuits successfully",
    ],
    readingIncludes: [
      "Relationship harmony analysis",
      "Decision-making guidance",
      "Social skills enhancement",
      "Beauty and art guidance",
      "Balance restoration techniques",
    ],
    strengths: ["Diplomatic", "Social", "Fair", "Cooperative"],
    challenges: ["Indecisive", "Avoids confrontation", "Self-pity"],
  },
  {
    id: 8,
    name: "Scorpio",
    date: "Oct 23 - Nov 21",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-q.jpg",
    description: "Passion and transformation await you.",
    traits: [
      "Passionate",
      "Mysterious",
      "Determined",
      "Intense",
      "Resourceful",
    ],
    element: "Water",
    planet: "Pluto & Mars",
    symbol: "♏",
    luckyColor: "Maroon",
    luckyNumber: 8,
    compatibility: ["Cancer", "Pisces", "Virgo"],
    benefits: [
      "Understand deep emotions and hidden desires",
      "Transform challenges into strengths effectively",
      "Enhance intuition and self-control abilities",
      "Plan personal growth with confidence and power",
      "Heal emotional wounds and past traumas",
    ],
    readingIncludes: [
      "Deep emotional analysis",
      "Transformation guidance",
      "Intuition development",
      "Personal power enhancement",
      "Healing and renewal techniques",
    ],
    strengths: ["Passionate", "Determined", "Intuitive", "Brave"],
    challenges: ["Jealous", "Secretive", "Resentful"],
  },
  {
    id: 9,
    name: "Sagittarius",
    date: "Nov 22 - Dec 21",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-m.jpg",
    description: "Adventure and optimism will thrive.",
    traits: [
      "Optimistic",
      "Independent",
      "Philosophical",
      "Adventurous",
      "Honest",
    ],
    element: "Fire",
    planet: "Jupiter",
    symbol: "♐",
    luckyColor: "Purple",
    luckyNumber: 3,
    compatibility: ["Aries", "Leo", "Aquarius"],
    benefits: [
      "Discover your life purpose and true direction",
      "Enhance optimism and positive decision-making",
      "Balance freedom with responsibility wisely",
      "Strengthen education and learning capabilities",
      "Plan global expansion and career opportunities",
    ],
    readingIncludes: [
      "Life purpose discovery",
      "Adventure and travel guidance",
      "Educational planning",
      "Optimism enhancement",
      "Freedom and responsibility balance",
    ],
    strengths: ["Optimistic", "Honest", "Intellectual", "Adventurous"],
    challenges: ["Impatient", "Tactless", "Restless"],
  },
  {
    id: 10,
    name: "Capricorn",
    date: "Dec 22 - Jan 19",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-hh.jpg",
    description: "Discipline and persistence will pay off.",
    traits: [
      "Disciplined",
      "Responsible",
      "Goal-Oriented",
      "Patient",
      "Ambitious",
    ],
    element: "Earth",
    planet: "Saturn",
    symbol: "♑",
    luckyColor: "Brown",
    luckyNumber: 4,
    compatibility: ["Taurus", "Virgo", "Scorpio"],
    benefits: [
      "Strengthen determination and patience",
      "Achieve career and financial success",
      "Improve time management and organization",
      "Balance work with emotional well-being",
      "Overcome professional challenges strategically",
    ],
    readingIncludes: [
      "Career success planning",
      "Financial growth strategies",
      "Time management techniques",
      "Professional development",
      "Life balance guidance",
    ],
    strengths: ["Responsible", "Disciplined", "Patient", "Ambitious"],
    challenges: ["Pessimistic", "Rigid", "Cold"],
  },
  {
    id: 11,
    name: "Aquarius",
    date: "Jan 20 - Feb 18",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-ppp.jpg",
    description: "Innovation and originality are key.",
    traits: [
      "Innovative",
      "Humanitarian",
      "Visionary",
      "Independent",
      "Intellectual",
    ],
    element: "Air",
    planet: "Uranus & Saturn",
    symbol: "♒",
    luckyColor: "Blue",
    luckyNumber: 7,
    compatibility: ["Gemini", "Libra", "Sagittarius"],
    benefits: [
      "Unlock creative and unique ideas",
      "Enhance social and humanitarian impact",
      "Improve adaptability and flexibility",
      "Strengthen intellectual growth and learning",
      "Plan futuristic goals and innovations",
    ],
    readingIncludes: [
      "Innovation and creativity guidance",
      "Social impact planning",
      "Intellectual development",
      "Future planning strategies",
      "Humanitarian work guidance",
    ],
    strengths: ["Progressive", "Original", "Humanitarian", "Independent"],
    challenges: ["Emotionally detached", "Stubborn", "Unpredictable"],
  },
  {
    id: 12,
    name: "Pisces",
    date: "Feb 19 - Mar 20",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-pp.png",
    description: "Imagination and compassion lead the way.",
    traits: ["Empathetic", "Intuitive", "Dreamy", "Compassionate", "Artistic"],
    element: "Water",
    planet: "Neptune & Jupiter",
    symbol: "♓",
    luckyColor: "Sea Green",
    luckyNumber: 11,
    compatibility: ["Cancer", "Scorpio", "Taurus"],
    benefits: [
      "Enhance spiritual awareness and connection",
      "Balance emotions with logical thinking",
      "Boost creativity and intuitive abilities",
      "Heal emotional wounds and past traumas",
      "Plan personal and spiritual growth journey",
    ],
    readingIncludes: [
      "Spiritual growth guidance",
      "Creative expression techniques",
      "Emotional healing practices",
      "Intuition development",
      "Compassionate living guidance",
    ],
    strengths: ["Compassionate", "Artistic", "Intuitive", "Gentle"],
    challenges: ["Over-sensitive", "Escapist", "Victim mentality"],
  },
];

export const astrologers = [
  {
    id: 1,
    name: "Priya Sharma",
    experience: "12+ years",
    specialization: "Vedic Astrology & Palmistry",
    rating: 4.9,
    reviews: 1247,
    expertise: [
      "Career Guidance",
      "Relationship Compatibility",
      "Financial Planning",
      "Marriage Prospects",
    ],
    languages: ["Hindi", "English", "Punjabi"],
    image: "/astrologers/priya-sharma.jpg",
    whatsappNumber: "+919876543210",
    about:
      "Renowned Vedic astrologer with 12+ years of experience in helping people find their true path through ancient astrological principles. Specialized in career guidance and relationship compatibility.",
    successRate: "95%",
    clientsHelped: "5000+",
    consultationFee: "₹799",
    responseTime: "Within 15 minutes",
    availability: "24/7",
    skills: [
      "Kundli Analysis",
      "Muhurta",
      "Gemstone Recommendation",
      "Vastu Shastra",
    ],
  },
  {
    id: 2,
    name: "Rajesh Kumar",
    experience: "15+ years",
    specialization: "Numerology & KP Astrology",
    rating: 4.8,
    reviews: 892,
    expertise: [
      "Marriage Compatibility",
      "Business Growth",
      "Health Issues",
      "Legal Matters",
    ],
    languages: ["Hindi", "Tamil", "English", "Telugu"],
    image: "/astrologers/rajesh-kumar.jpg",
    whatsappNumber: "+919876543211",
    about:
      "Expert in numerology and KP astrology system, specializing in accurate predictions and practical solutions for life challenges. Known for precise business and marriage predictions.",
    successRate: "92%",
    clientsHelped: "4200+",
    consultationFee: "₹699",
    responseTime: "Within 20 minutes",
    availability: "24/7",
    skills: [
      "Numerology",
      "KP System",
      "Horary Astrology",
      "Remedial Measures",
    ],
  },
  {
    id: 3,
    name: "Anita Desai",
    experience: "8+ years",
    specialization: "Tarot Reading & Crystal Healing",
    rating: 4.7,
    reviews: 567,
    expertise: [
      "Love Problems",
      "Spiritual Growth",
      "Career Transition",
      "Personal Development",
    ],
    languages: ["English", "Marathi", "Hindi", "Gujarati"],
    image: "/astrologers/anita-desai.jpg",
    whatsappNumber: "+919876543212",
    about:
      "Combining tarot wisdom with crystal healing to provide holistic guidance and transformative solutions for modern life challenges. Special focus on spiritual and personal growth.",
    successRate: "90%",
    clientsHelped: "3000+",
    consultationFee: "₹899",
    responseTime: "Within 10 minutes",
    availability: "24/7",
    skills: [
      "Tarot Reading",
      "Crystal Healing",
      "Meditation Guidance",
      "Energy Healing",
    ],
  },
  {
    id: 4,
    name: "Dr. Vikram Singh",
    experience: "20+ years",
    specialization: "Medical Astrology & Prashna",
    rating: 4.9,
    reviews: 1563,
    expertise: [
      "Health Issues",
      "Medical Astrology",
      "Prashna Kundli",
      "Remedial Astrology",
    ],
    languages: ["Hindi", "English", "Sanskrit"],
    image: "/astrologers/vikram-singh.jpg",
    whatsappNumber: "+919876543213",
    about:
      "Doctorate in Vedic astrology with specialization in medical astrology and Prashna. Known for accurate health predictions and effective remedial solutions.",
    successRate: "96%",
    clientsHelped: "6800+",
    consultationFee: "₹999",
    responseTime: "Within 30 minutes",
    availability: "10 AM - 8 PM",
    skills: [
      "Medical Astrology",
      "Prashna",
      "Mantra Therapy",
      "Yagya Recommendations",
    ],
  },
  {
    id: 5,
    name: "Meera Patel",
    experience: "10+ years",
    specialization: "Love & Relationship Astrology",
    rating: 4.8,
    reviews: 734,
    expertise: [
      "Love Marriage",
      "Relationship Issues",
      "Family Problems",
      "Divorce Guidance",
    ],
    languages: ["Hindi", "English", "Gujarati", "Marathi"],
    image: "/astrologers/meera-patel.jpg",
    whatsappNumber: "+919876543214",
    about:
      "Specialized in love and relationship astrology with proven track record of helping thousands find love and resolve relationship issues. Compassionate and understanding approach.",
    successRate: "94%",
    clientsHelped: "3500+",
    consultationFee: "₹749",
    responseTime: "Within 15 minutes",
    availability: "24/7",
    skills: [
      "Relationship Analysis",
      "Compatibility Matching",
      "Love Remedies",
      "Marriage Counseling",
    ],
  },
  {
    id: 6,
    name: "Arjun Mehta",
    experience: "7+ years",
    specialization: "Career & Business Astrology",
    rating: 4.7,
    reviews: 423,
    expertise: [
      "Career Growth",
      "Business Success",
      "Job Change",
      "Investment Guidance",
    ],
    languages: ["Hindi", "English", "Bengali"],
    image: "/astrologers/arjun-mehta.jpg",
    whatsappNumber: "+919876543215",
    about:
      "Young and dynamic astrologer specializing in career and business predictions. Known for practical advice and modern approach to traditional astrology.",
    successRate: "91%",
    clientsHelped: "2200+",
    consultationFee: "₹649",
    responseTime: "Within 10 minutes",
    availability: "24/7",
    skills: [
      "Career Prediction",
      "Business Horoscope",
      "Financial Astrology",
      "Remedial Solutions",
    ],
  },
];

export const readingPackages = [
  {
    id: 1,
    name: "Basic Reading",
    price: "₹499",
    duration: "30 minutes",
    features: [
      "Basic personality analysis",
      "Current month predictions",
      "General guidance",
      "2 specific questions answered",
    ],
    bestFor: "Quick insights and general guidance",
  },
  {
    id: 2,
    name: "Premium Reading",
    price: "₹999",
    duration: "60 minutes",
    features: [
      "Detailed personality analysis",
      "3 months detailed predictions",
      "Career and relationship guidance",
      "Unlimited questions",
      "Personalized remedies",
    ],
    bestFor: "Comprehensive life analysis",
  },
  {
    id: 3,
    name: "Yearly Package",
    price: "₹4999",
    duration: "Whole year support",
    features: [
      "Complete birth chart analysis",
      "Yearly horoscope 2024",
      "Monthly follow-up sessions",
      "24/7 chat support",
      "Emergency consultation",
      "All remedies included",
    ],
    bestFor: "Year-long guidance and support",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Rahul Verma",
    zodiac: "Aries",
    rating: 5,
    comment:
      "Priya Sharma's guidance transformed my career. Her predictions were accurate and remedies worked wonders!",
    date: "2 weeks ago",
  },
  {
    id: 2,
    name: "Priya Patel",
    zodiac: "Cancer",
    rating: 5,
    comment:
      "Rajesh Kumar helped me through my relationship crisis. His numerology analysis was spot on!",
    date: "1 month ago",
  },
  {
    id: 3,
    name: "Ankit Singh",
    zodiac: "Leo",
    rating: 5,
    comment:
      "Anita's tarot reading gave me clarity during my career transition. Highly recommended!",
    date: "3 weeks ago",
  },
];
