import { Product } from "@/components/Products/ProductListing";


export const allProducts: Product[] = [
  {
    id: 1,
    name: "Raksha Kavach Bracelet",
    price: 120.23,
    image: "/images/Bracelets/IMG_1.heic",
    images: [
      "/images/Bracelets/IMG_1.heic",
      "/images/Bracelets/IMG_2.heic",
      "/images/Bracelets/IMG_3.heic",
      "/images/Bracelets/IMG_4.heic",
    ],
    category: "Dresses",
    brand: "H&M",
    size: ["Medium", "Large"],
    gender: ["Women", "Girls"],
    isNew: true,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Golden Thread Bracelet",
    price: 150.0,
    image: "/images/Bracelets/IMG_5.heic",
    images: [
      "/images/Bracelets/IMG_5.heic",
      "/images/Bracelets/IMG_6.heic",
      "/images/Bracelets/IMG_7.heic",
    ],
    category: "Tops",
    brand: "Zara",
    size: ["Large", "Plus Size"],
    gender: ["Women", "Ladies"],
    isNew: false,
    rating: 4.2,
  },
  {
    id: 3,
    name: "Silver Charm Bracelet",
    price: 180.5,
    image: "/images/Bracelets/IMG_8.heic",
    images: [
      "/images/Bracelets/IMG_8.heic",
      "/images/Bracelets/IMG_9.heic",
      "/images/Bracelets/IMG_10.heic",
      "/images/Bracelets/IMG_11.heic",
    ],
    category: "Lingerie & Lounge Wear",
    brand: "Victoria's Secret",
    size: ["Medium"],
    gender: ["Women"],
    isNew: true,
    rating: 4.8,
  },
  {
    id: 4,
    name: "Beaded Bracelet",
    price: 90.0,
    image: "/images/Bracelets/IMG_12.heic",
    images: [
      "/images/Bracelets/IMG_12.heic",
      "/images/Bracelets/IMG_13.heic",
      "/images/Bracelets/IMG_14.heic",
    ],
    category: "Blouse",
    brand: "Mark & Spencer",
    size: ["Large", "Plus Size", "Sexy Plus Size"],
    gender: ["Ladies"],
    isNew: false,
    rating: 3.9,
  },
  {
    id: 5,
    name: "Leather Strap Bracelet",
    price: 200.0,
    image: "/images/Bracelets/IMG_15.heic",
    images: [
      "/images/Bracelets/IMG_15.heic",
      "/images/Bracelets/IMG_16.heic",
      "/images/Bracelets/IMG_17.heic",
      "/images/Bracelets/IMG_18.heic",
    ],
    category: "Vintage",
    brand: "Gucci",
    size: ["Medium", "Large"],
    gender: ["Women", "Ladies"],
    isNew: true,
    rating: 4.7,
  },
  {
    id: 6,
    name: "Pearl Bracelet",
    price: 250.5,
    image: "/images/Bracelets/IMG_19.heic",
    images: [
      "/images/Bracelets/IMG_19.heic",
      "/images/Bracelets/IMG_20.heic",
      "/images/Bracelets/IMG_21.heic",
    ],
    category: "Dresses",
    brand: "Chanel",
    size: ["Medium"],
    gender: ["Women"],
    isNew: false,
    rating: 4.9,
  },
  {
    id: 7,
    name: "Thread Friendship Bracelet",
    price: 75.0,
    image: "/images/Bracelets/IMG_22.heic",
    images: [
      "/images/Bracelets/IMG_22.heic",
      "/images/Bracelets/IMG_23.heic",
      "/images/Bracelets/IMG_24.heic",
      "/images/Bracelets/IMG_25.heic",
    ],
    category: "Tops",
    brand: "H&M",
    size: ["Large", "Plus Size"],
    gender: ["Girls", "Babies"],
    isNew: true,
    rating: 4.1,
  },
  {
    id: 8,
    name: "Gold Plated Bracelet",
    price: 300.0,
    image: "/images/Bracelets/IMG_26.heic",
    images: [
      "/images/Bracelets/IMG_26.heic",
      "/images/Bracelets/IMG_27.heic",
      "/images/Bracelets/IMG_28.heic",
    ],
    category: "Lingerie & Lounge Wear",
    brand: "Dior",
    size: ["Medium", "Large", "Sexy Plus Size"],
    gender: ["Women", "Ladies"],
    isNew: false,
    rating: 4.6,
  },
  {
    id: 9,
    name: "Classic Woven Bracelet",
    price: 110.0,
    image: "/images/Bracelets/IMG_29.heic",
    images: [
      "/images/Bracelets/IMG_29.heic",
      "/images/Bracelets/IMG_30.heic",
      "/images/Bracelets/IMG_31.heic",
      "/images/Bracelets/IMG_32.heic",
    ],
    category: "Blouse",
    brand: "Prada",
    size: ["Medium"],
    gender: ["Women"],
    isNew: true,
    rating: 4.3,
  },
  {
    id: 10,
    name: "Mystic Stone Bracelet",
    price: 175.0,
    image: "/images/Bracelets/IMG_33.heic",
    images: [
      "/images/Bracelets/IMG_33.heic",
      "/images/Bracelets/IMG_34.heic",
      "/images/Bracelets/IMG_35.heic",
    ],
    category: "Vintage",
    brand: "Fendi",
    size: ["Large", "Plus Size"],
    gender: ["Ladies"],
    isNew: false,
    rating: 4.4,
  },
  {
    id: 11,
    name: "Diamond Elegance Bracelet",
    price: 280.0,
    image: "/images/Bracelets/IMG_36.heic",
    images: [
      "/images/Bracelets/IMG_36.heic",
      "/images/Bracelets/IMG_37.heic",
      "/images/Bracelets/IMG_38.heic",
      "/images/Bracelets/IMG_39.heic",
    ],
    category: "Dresses",
    brand: "Versace",
    size: ["Medium"],
    gender: ["Women"],
    isNew: true,
    rating: 4.9,
  },
  {
    id: 12,
    name: "Rose Gold Beauty",
    price: 195.0,
    image: "/images/Bracelets/IMG_40.heic",
    images: [
      "/images/Bracelets/IMG_40.heic",
      "/images/Bracelets/IMG_41.heic",
      "/images/Bracelets/IMG_42.heic",
    ],
    category: "Tops",
    brand: "Dolce & Gabbana",
    size: ["Large", "Sexy Plus Size"],
    gender: ["Ladies"],
    isNew: false,
    rating: 4.5,
  },
];
