export const allProducts = [
  {
    id: 1,
    name: "Raksha Kavach Bracelet",
    price: 120.23,
    image: "https://picsum.photos/id/1011/300/300",
    category: "Dresses",
    brand: "H&M",
    size: ["Medium", "Large"],
    gender: ["Women", "Girls"],
    isNew: true,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Golden Thread Bracelet",
    price: 150.0,
    image: "https://picsum.photos/id/1012/300/300",
    category: "Tops",
    brand: "Zara",
    size: ["Large", "Plus Size"],
    gender: ["Women", "Ladies"],
    isNew: false,
    rating: 4.2,
  },
  {
    id: 3,
    name: "Silver Charm Bracelet",
    price: 180.5,
    image: "https://picsum.photos/id/1013/300/300",
    category: "Lingerie & Lounge Wear",
    brand: "Victoria's Secret",
    size: ["Medium"],
    gender: ["Women"],
    isNew: true,
    rating: 4.8,
  },
  {
    id: 4,
    name: "Beaded Bracelet",
    price: 90.0,
    image: "https://picsum.photos/id/1015/300/300",
    category: "Blouse",
    brand: "Mark & Spencer",
    size: ["Large", "Plus Size", "Sexy Plus Size"],
    gender: ["Ladies"],
    isNew: false,
    rating: 3.9,
  },
  {
    id: 5,
    name: "Leather Strap Bracelet",
    price: 200.0,
    image: "https://picsum.photos/id/1016/300/300",
    category: "Vintage",
    brand: "Gucci",
    size: ["Medium", "Large"],
    gender: ["Women", "Ladies"],
    isNew: true,
    rating: 4.7,
  },
  {
    id: 6,
    name: "Pearl Bracelet",
    price: 250.5,
    image: "https://picsum.photos/id/1018/300/300",
    category: "Dresses",
    brand: "Chanel",
    size: ["Medium"],
    gender: ["Women"],
    isNew: false,
    rating: 4.9,
  },
  {
    id: 7,
    name: "Thread Friendship Bracelet",
    price: 75.0,
    image: "https://picsum.photos/id/1020/300/300",
    category: "Tops",
    brand: "H&M",
    size: ["Large", "Plus Size"],
    gender: ["Girls", "Babies"],
    isNew: true,
    rating: 4.1,
  },
  {
    id: 8,
    name: "Gold Plated Bracelet",
    price: 300.0,
    image: "https://picsum.photos/id/1021/300/300",
    category: "Lingerie & Lounge Wear",
    brand: "Dior",
    size: ["Medium", "Large", "Sexy Plus Size"],
    gender: ["Women", "Ladies"],
    isNew: false,
    rating: 4.6,
  },
  {
    id: 9,
    name: "Classic Woven Bracelet",
    price: 110.0,
    image: "https://picsum.photos/id/1024/300/300",
    category: "Blouse",
    brand: "Prada",
    size: ["Medium"],
    gender: ["Women"],
    isNew: true,
    rating: 4.3,
  },
  {
    id: 10,
    name: "Mystic Stone Bracelet",
    price: 175.0,
    image: "https://picsum.photos/id/1025/300/300",
    category: "Vintage",
    brand: "Fendi",
    size: ["Large", "Plus Size"],
    gender: ["Ladies"],
    isNew: false,
    rating: 4.4,
  },
  {
    id: 11,
    name: "Diamond Elegance Bracelet",
    price: 280.0,
    image: "https://picsum.photos/id/1027/300/300",
    category: "Dresses",
    brand: "Versace",
    size: ["Medium"],
    gender: ["Women"],
    isNew: true,
    rating: 4.9,
  },
  {
    id: 12,
    name: "Rose Gold Beauty",
    price: 195.0,
    image: "https://picsum.photos/id/1028/300/300",
    category: "Tops",
    brand: "Dolce & Gabbana",
    size: ["Large", "Sexy Plus Size"],
    gender: ["Ladies"],
    isNew: false,
    rating: 4.5,
  },
];